package br.com.fintech;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class CriadorDeTabelas {

    public static void main(String[] args) {
        String url = "jdbc:oracle:thin:@localhost:1521:xe"; // Altere se necessário
        String usuario = "SEU_USUARIO";
        String senha = "SUA_SENHA";

        try (Connection conn = DriverManager.getConnection(url, usuario, senha);
             Statement stmt = conn.createStatement()) {

            // Tabela de Usuários
            String sqlUsuarios = """
                CREATE TABLE USUARIOS (
                    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    NOME VARCHAR2(100) NOT NULL,
                    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
                    SENHA VARCHAR2(100) NOT NULL
                )
            """;

            // Tabela de Transações
            String sqlTransacoes = """
                CREATE TABLE TRANSACOES (
                    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    TIPO VARCHAR2(50) NOT NULL,
                    VALOR NUMBER(10, 2) NOT NULL,
                    DATA_TRANSACAO DATE NOT NULL,
                    USUARIO_ID NUMBER NOT NULL,
                    CONSTRAINT FK_TRANSACAO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
                )
            """;

            // Tabela de Relatórios
            String sqlRelatorios = """
                CREATE TABLE RELATORIOS (
                    MES VARCHAR2(20) PRIMARY KEY,
                    TOTAL_RECEITAS NUMBER(10, 2) DEFAULT 0,
                    TOTAL_DESPESAS NUMBER(10, 2) DEFAULT 0
                )
            """;

            stmt.execute(sqlUsuarios);
            stmt.execute(sqlTransacoes);
            stmt.execute(sqlRelatorios);

            System.out.println("✅ Tabelas criadas com sucesso!");

        } catch (SQLException e) {
            System.err.println("❌ Erro ao criar tabelas: " + e.getMessage());
        }
    }
}
